spring:
  application:
    name: blog-web-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${prod.mysql.hostname}:${prod.mysql.port}/${prod.mysql.database-name}?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: ${prod.mysql.username}
    password: ${prod.mysql.password}
    hikari:
      idle-timeout: 10000
      max-lifetime: 28000000
      connection-timeout: 10000
      validation-timeout: 10000
  jpa:
    hibernate:
      ddl-auto: validate
    generate-ddl: false
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        format_sql: true
  rabbitmq:
    host: ${prod.rabbitmq.hostname}
    port: ${prod.rabbitmq.port}
    username: ${prod.rabbitmq.username}
    password: ${prod.rabbitmq.password}
  redis:
    host: ${prod.redis.hostname}
    port: ${prod.redis.port}
    password: ${prod.redis.password}
    database: 0
  servlet:
    multipart:
      enabled: true
      max-file-size: 128MB
      max-request-size: 128MB

logging:
  level:
    com.anthonykim.blog: info
    org:
      hibernate: info
      springframework:
        amqp:
          rabbit: info

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh

server:
  port: ${prod.server.port}
  error:
    include-message: always

grpc:
  server:
    port: ${prod.grpc.server.port}
  client:
    blog-log-service:
      address: static://${prod.grpc.client.blog-log-service.hostname}:${prod.grpc.client.blog-log-service.port}
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
